export const week_days = {
	'Sun': 'Domingo',
	'Mon': 'Segunda',
	'Tue': 'Terça',
	'Wed': 'Quarta',
	'Thu': 'Quinta',
	'Fri': 'Sexta',
	'Sat': 'Sábado'
}

export const code_condition = {
	0: 'Tornado',
	1: 'Tempestade Tropical',
	2: 'Furacão',
	3: 'severe thunderstorms',
	4: 'thunderstorms',
	5: 'Chuva e Neve',
	6: 'mixed rain and sleet',
	7: 'mixed snow and sleet',
	8: 'freezing drizzle',
	9: 'drizzle',
	10: 'freezing rain',
	11:	'showers',
	12:	'showers',
	13:	'snow flurries',
	14:	'light snow showers',
	15:	'blowing snow',
	16:	'snow',
	17:	'hail',
	18:	'sleet',
	19:	'dust',
	20:	'foggy',
	21:	'haze',
	22:	'smoky',
	23:	'Ventos Fortes',
	24:	'windy',
	25:	'Frio',
	26:	'Nublado',
	27:	'Muitas Nuvens',
	28:	'Muitas Nuvens',
	29:	'Parcialmente Nublado',
	30:	'Parcialmente Nublado',
	31:	'Noite Clara',
	32:	'Ensolarado',
	33:	'Noite Amena',
	34:	'Dia Ameno',
	35:	'mixed rain and hail',
	36:	'Quente',
	37:	'isolated thunderstorms',
	38:	'scattered thunderstorms',
	39:	'scattered thunderstorms',
	40:	'scattered showers',
	41:	'heavy snow',
	42:	'scattered snow showers',
	43:	'heavy snow',
	44:	'Parcialmente Nublado',
	45:	'thundershowers',
	46:	'snow showers',
	47:	'isolated thundershowers',
	3200: 'Não disponível'
}


